# Generated by Django 5.2.9 on 2026-10-07 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_type", models.CharField(max_length=100)),
                ("subject_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submit"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("request_changes", "Request changes"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "default_permissions": ("view",),
            },
        ),
    ]
