# Generated by Django 5.2.9 on 2026-10-07 02:23

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        ("programme", "0006_alter_day_options_alter_edition_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official_site", "Official site"),
                            ("news_outlet", "News outlet"),
                            ("archive", "Archive"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2000)),
                ("is_official", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Int"),
                            ("bool", "Bool"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("scraped", "Scraped"),
                            ("manual", "Manual"),
                            ("community", "Community"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "staged_changes",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "quarantine_file",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("year_approx", models.PositiveIntegerField(blank=True, null=True)),
                ("title_es", models.CharField(max_length=300)),
                ("title_en", models.CharField(blank=True, default="", max_length=300)),
                ("description_es", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                ("author", models.CharField(blank=True, default="", max_length=300)),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("license", models.CharField(blank=True, default="", max_length=200)),
                ("citation_text", models.TextField(blank=True, default="")),
                (
                    "rights_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("permitted", "Permitted"),
                            ("licensed", "Licensed"),
                            ("public_domain", "Public domain"),
                            ("permission_on_file", "Permission on file"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("exif_stripped", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("minor_subject", models.BooleanField(default=False)),
                ("guardian_consent_on_file", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="programme.edition",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year_approx", "title_es"],
                "permissions": (
                    ("publish_mediaasset", "Can publish mediaasset"),
                    ("reject_mediaasset", "Can reject mediaasset"),
                    ("unpublish_mediaasset", "Can unpublish mediaasset"),
                    ("request_changes_mediaasset", "Can request changes to mediaasset"),
                ),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "rejected"), _negated=True),
                            models.Q(("rejection_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="editorial_mediaasset_rejection_reason_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "published"), _negated=True),
                            models.Q(
                                models.Q(("rights_status", "unknown"), _negated=True),
                                models.Q(("author", ""), _negated=True),
                                models.Q(("source_ref", ""), _negated=True),
                                models.Q(("citation_text", ""), _negated=True),
                                ("exif_stripped", True),
                            ),
                            _connector="OR",
                        ),
                        name="media_publishable_requires_rights",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "published"), _negated=True),
                            models.Q(("minor_subject", True), _negated=True),
                            ("guardian_consent_on_file", True),
                            _connector="OR",
                        ),
                        name="media_minor_requires_consent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("scraped", "Scraped"),
                            ("manual", "Manual"),
                            ("community", "Community"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "staged_changes",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(max_length=300)),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("outlet", models.CharField(blank=True, default="", max_length=200)),
                ("published_on", models.DateField(blank=True, null=True)),
                ("summary_es", models.TextField(blank=True, default="")),
                ("summary_en", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_items",
                        to="editorial.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_on", "headline"],
                "permissions": (
                    ("publish_newsitem", "Can publish newsitem"),
                    ("reject_newsitem", "Can reject newsitem"),
                    ("unpublish_newsitem", "Can unpublish newsitem"),
                    ("request_changes_newsitem", "Can request changes to newsitem"),
                ),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "rejected"), _negated=True),
                            models.Q(("rejection_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="editorial_newsitem_rejection_reason_required",
                    )
                ],
            },
        ),
    ]
