# Generated by Django 5.2.17 on 2026-10-07 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editorial", "0001_initial"),
        ("ingestion", "0001_initial"),
        ("programme", "0006_alter_day_options_alter_edition_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash", ""), _negated=True),
                fields=("content_hash",),
                name="editorial_mediaasset_content_hash_unique",
            ),
        ),
    ]
