# Generated by Django 5.2.9 on 2026-10-06 18:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
        ("programme", "0003_remove_edition_is_published_day_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ingestion.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ingestion.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ingestion.ingestionrun",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("scraped", "Scraped"),
                            ("manual", "Manual"),
                            ("community", "Community"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("title_es", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, default="", max_length=200)),
                ("description_es", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="programme.day",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="programme.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["day__date", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["day", "sort_order"],
                        name="programme_e_day_id_5bfb02_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "rejected"), _negated=True),
                            models.Q(("rejection_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="programme_event_rejection_reason_required",
                    )
                ],
            },
        ),
    ]
