# Generated by Django 5.2.9 on 2026-10-06 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
        ("programme", "0004_day_ingestion_run_edition_ingestion_run_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source_record_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_record_key", ""), _negated=True),
                fields=("day", "source_record_key"),
                name="event_day_source_key_unique",
            ),
        ),
    ]
