# Generated by Django 5.2.9 on 2026-10-07 02:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0005_event_source_record_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "ordering": ["date"],
                "permissions": (
                    ("publish_day", "Can publish day"),
                    ("reject_day", "Can reject day"),
                    ("unpublish_day", "Can unpublish day"),
                    ("request_changes_day", "Can request changes to day"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="edition",
            options={
                "ordering": ["year"],
                "permissions": (
                    ("publish_edition", "Can publish edition"),
                    ("reject_edition", "Can reject edition"),
                    ("unpublish_edition", "Can unpublish edition"),
                    ("request_changes_edition", "Can request changes to edition"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["day__date", "sort_order"],
                "permissions": (
                    ("publish_event", "Can publish event"),
                    ("reject_event", "Can reject event"),
                    ("unpublish_event", "Can unpublish event"),
                    ("request_changes_event", "Can request changes to event"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={
                "ordering": ["name_es"],
                "permissions": (
                    ("publish_venue", "Can publish venue"),
                    ("reject_venue", "Can reject venue"),
                    ("unpublish_venue", "Can unpublish venue"),
                    ("request_changes_venue", "Can request changes to venue"),
                ),
            },
        ),
        migrations.AddField(
            model_name="day",
            name="staged_changes",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="staged_changes",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="staged_changes",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="staged_changes",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
