# Generated by Django 5.2.17 on 2026-10-07 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
        ("programme", "0006_alter_day_options_alter_edition_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="day",
            name="day_edition_slug_unique",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="slug",
            new_name="slug_es",
        ),
        migrations.RenameField(
            model_name="edition",
            old_name="slug",
            new_name="slug_es",
        ),
        migrations.AddField(
            model_name="day",
            name="slug_en",
            field=models.SlugField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="edition",
            name="slug_en",
            field=models.SlugField(blank=True, default="", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                fields=("edition", "slug_es"), name="day_edition_slug_es_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug_en", ""), _negated=True),
                fields=("edition", "slug_en"),
                name="day_edition_slug_en_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug_en", ""), _negated=True),
                fields=("slug_en",),
                name="edition_slug_en_unique",
            ),
        ),
    ]
