# Generated by Django 5.2.9 on 2026-10-06 18:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=2000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("wp_api", "WordPress REST API"),
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "wp_object_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "wp_object_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("selectors", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit_seconds", models.PositiveIntegerField(default=60)),
                (
                    "schedule_cron",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RawDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("http_status", models.PositiveSmallIntegerField()),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("storage_key", models.CharField(max_length=1000)),
                ("fetched_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scrape_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_documents",
                        to="ingestion.scrapesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("cron", "Scheduled"),
                            ("manual", "Manual"),
                            ("admin", "Admin"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scrape_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="ingestion.scrapesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
