# Generated by Django 5.2.9 on 2026-10-07 02:30

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TakedownRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                (
                    "requester_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("requester_email", models.EmailField(max_length=254)),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("copyright", "Copyright"),
                            ("privacy", "Privacy"),
                            ("illegal_content", "Illegal content"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("in_review", "In review"),
                            ("actioned", "Actioned"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("action_taken", models.TextField(blank=True, default="")),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms"),
                            ("privacy", "Privacy"),
                            ("content_policy", "Content policy"),
                            ("takedown", "Takedown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=16)),
                ("locale", models.CharField(max_length=2)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["doc_type", "-effective_from"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("doc_type", "locale"),
                        name="legal_one_current_per_type_locale",
                    )
                ],
            },
        ),
    ]
