# Generated by Django 5.2.9 on 2026-10-07 02:30

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import carnaval.submissions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        ("legal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("scraped", "Scraped"),
                            ("manual", "Manual"),
                            ("community", "Community"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "staged_changes",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_token",
                    models.CharField(
                        default=carnaval.submissions.models.generate_public_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video_link", "Video link")],
                        max_length=16,
                    ),
                ),
                (
                    "declared_author",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("declared_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "declared_place",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("description_es", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                (
                    "video_provider",
                    models.CharField(
                        blank=True,
                        choices=[("youtube", "YouTube"), ("vimeo", "Vimeo")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("video_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "permissions": (
                    ("publish_submission", "Can publish submission"),
                    ("reject_submission", "Can reject submission"),
                    ("unpublish_submission", "Can unpublish submission"),
                    ("request_changes_submission", "Can request changes to submission"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "user_agent_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("declaration_minor_subject", models.BooleanField(default=False)),
                ("declaration_rights", models.BooleanField(default=False)),
                (
                    "legal_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="legal.legaldocument",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quarantine_key", models.CharField(max_length=1000)),
                ("mime_detected", models.CharField(max_length=100)),
                (
                    "declared_mime",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("byte_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("exif_stripped", models.BooleanField(default=False)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="submissions.submissionfile",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    models.Q(("rejection_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="submissions_submission_rejection_reason_required",
            ),
        ),
    ]
